"""fix models schema

Revision ID: 0a6cc5648550
Revises: aa0e9d967af3
Create Date: 2026-04-23 13:52:27.038946

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '0a6cc5648550'
down_revision: Union[str, Sequence[str], None] = 'aa0e9d967af3'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('sources',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('type', sa.String(), nullable=False),
    sa.Column('config', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('news_delivery',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('telegram_id', sa.Integer(), nullable=False),
    sa.Column('news_id', sa.Integer(), nullable=False),
    sa.Column('status', sa.Boolean(), server_default=sa.text('false'), nullable=False),
    sa.Column('send_at', sa.TIMESTAMP(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['news_id'], ['news.id'], ),
    sa.ForeignKeyConstraint(['telegram_id'], ['users.telegram_id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.add_column('news', sa.Column('source_id', sa.Integer(), nullable=False))
    op.create_foreign_key(None, 'news', 'sources', ['source_id'], ['id'])
    op.drop_column('news', 'source')
    op.add_column('subscriptions', sa.Column('source_id', sa.Integer(), nullable=False))
    op.add_column('subscriptions', sa.Column('updated_at', sa.TIMESTAMP(), server_default=sa.text('now()'), nullable=False))
    op.drop_constraint(op.f('uq_subscription_telegram_source'), 'subscriptions', type_='unique')
    op.create_unique_constraint('uq_subscription_telegram_source', 'subscriptions', ['telegram_id', 'source_id'])
    op.create_foreign_key(None, 'subscriptions', 'sources', ['source_id'], ['id'])
    op.drop_column('subscriptions', 'source')
    op.drop_column('subscriptions', 'update_at')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('subscriptions', sa.Column('update_at', postgresql.TIMESTAMP(), server_default=sa.text('now()'), autoincrement=False, nullable=False))
    op.add_column('subscriptions', sa.Column('source', sa.VARCHAR(), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'subscriptions', type_='foreignkey')
    op.drop_constraint('uq_subscription_telegram_source', 'subscriptions', type_='unique')
    op.create_unique_constraint(op.f('uq_subscription_telegram_source'), 'subscriptions', ['telegram_id', 'source'], postgresql_nulls_not_distinct=False)
    op.drop_column('subscriptions', 'updated_at')
    op.drop_column('subscriptions', 'source_id')
    op.add_column('news', sa.Column('source', sa.VARCHAR(), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'news', type_='foreignkey')
    op.drop_column('news', 'source_id')
    op.drop_table('news_delivery')
    op.drop_table('sources')
    # ### end Alembic commands ###
