"""add new columns to users and subscriptions

Revision ID: aa0e9d967af3
Revises: 6adc4229f36e
Create Date: 2026-04-20 23:58:32.993609

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'aa0e9d967af3'
down_revision: Union[str, Sequence[str], None] = '6adc4229f36e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('subscriptions', sa.Column('is_active', sa.Boolean(), nullable=False))
    op.add_column('subscriptions', sa.Column('update_at', sa.TIMESTAMP(), server_default=sa.text('now()'), nullable=False))
    op.add_column('users', sa.Column('created_at', sa.TIMESTAMP(), server_default=sa.text('now()'), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'created_at')
    op.drop_column('subscriptions', 'update_at')
    op.drop_column('subscriptions', 'is_active')
    # ### end Alembic commands ###
